services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    command: dotnet watch run --urls=http://0.0.0.0:80
    volumes:
      - ./api:/src
    container_name: event_api
    ports:
      - "5000:80"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+80
      - Cors__Origins=http://localhost:5173
      - ConnectionStrings_DefaultConnection=Host=postgres;Port=5432;Database=eventsdb;Username=postgres;Password=password123
  postgres:
    image: postgres:15
    container_name: event_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: eventsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  front:
    build:
      context: ./front  # или промени ако ти је други назив фасцикле
      dockerfile: Dockerfile
    container_name: event_front
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  pgdata:   
